# Generated by Django 5.2.5 on 2025-09-02 15:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_dataset_column_types_dataset_feature_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='epochs',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='learning_rate',
            field=models.FloatField(default=0.001, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='test_pct',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='train_pct',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
