# Generated by Django 5.2.5 on 2025-09-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_trainingjob_created_at_trainingjob_epochs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('val_accuracy', models.FloatField(blank=True, null=True)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='registry.trainingjob')),
            ],
            options={
                'verbose_name': 'Training Metrics',
                'verbose_name_plural': 'Training Metrics',
            },
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
