# Generated by Django 5.2.5 on 2025-09-11 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_trainingmetrics_delete_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='test_pct',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='train_pct',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='batch_size',
            field=models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='val_split',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
