# Generated by Django 5.2.5 on 2025-09-18 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_trainingjob_test_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingArtifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('s3_uri', models.URLField()),
                ('sha256', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='registry.trainingjob')),
            ],
            options={
                'verbose_name': 'Training Artifact',
                'verbose_name_plural': 'Training Artifacts',
            },
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
    ]
