# Generated by Django 5.2.5 on 2025-09-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_trainingartifacts_delete_artifact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingartifacts',
            old_name='s3_uri',
            new_name='model_s3_uri',
        ),
        migrations.RemoveField(
            model_name='trainingartifacts',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='trainingartifacts',
            name='sha256',
        ),
        migrations.AddField(
            model_name='trainingartifacts',
            name='id2label_s3_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
