# Generated by Django 5.2.5 on 2025-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_rename_s3_uri_trainingartifacts_model_s3_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingartifacts',
            name='id2label_s3_uri',
        ),
        migrations.RemoveField(
            model_name='trainingartifacts',
            name='model_s3_uri',
        ),
        migrations.AddField(
            model_name='trainingartifacts',
            name='s3_uri',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
